Fix nephos build failed on libsai checking
*root cause:
    On commit 1e42517996bfe41ac58d4c25ee3f93502befcb9d
    add a AC_CHECK_LIB to check libsai is exist.

    The AC_CHECK_LIB will try to build libsai with test code, and got following fail message:
        g++ -o conftest -g -O2 -fdebug-prefix-map=/sonic/src/sonic-sairedis=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro conftest.cpp -lsai
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `pthread_create'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `sem_wait'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `sem_init'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `sem_destroy'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `pthread_attr_setstacksize'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `sem_post'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `sem_timedwait'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `pthread_mutexattr_settype'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `pthread_join'
        /usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libsai.so: undefined reference to `pthread_mutexattr_init'

    This is because libsai also need libpthread to build, but it not mention it in so file.
        $ readelf -d /usr/lib/libsai.so | grep NEEDED
        0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

    Other platform do mention it in so file (Broadcom for example):
            $ readelf -d /usr/lib/libsai.so.1 | grep NEED
        0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
        0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
        0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
        0x0000000000000001 (NEEDED)             Shared library: [libprotobuf.so.10]
        0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
        0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
        0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
        0x0000000000000001 (NEEDED)             S    hared library: [libgcc_s.so.1]
        0x000000006ffffffe (VERNEED)            0    x6ce7f0
        0x000000006fffffff (VERNEEDNUM)         7

*solution:
    Since libsai also need libpthread, modify the AC_CHECK_LIB to add libpthread to other-libraries.
    AC_CHECK_LIB (library, function, [action-if-found], [action-if-not-found], [other-libraries])